### ISSUE TITLE
Permission denied: 'config.json'

### ISSUE THREAD

**Issue by roharia** [edgeimpulse/edge-impulse-omniverse-ext#2]
### Problem
Ran into an issue where the config.json wasn't being generated or found. This may be related to the directory permissions where the config is supposed to be stored or needing Admin rights?

![image](https://github.com/edgeimpulse/edge-impulse-omniverse-ext/assets/109554486/ef9ee807-e6aa-4acf-b10b-bb0c1e709bb2)

### Setup
NVIDIA Omniverse in a Windows EC2 instance in AWS

### Fix
Disabling and enabling the extension didn't help, but reinstalling everything ended up fixing this issue.

**Comment by AlessandroEdge** [comment]
@roharia is this still relevant? cc @ferjm

**Comment by roharia** [comment]
Closing as the "fix" described above resolved the issue
